# MT6768 Device Configuration for TWRP Recovery

# Device and Vendor
TARGET_DEVICE := a05m
PRODUCT_DEVICE := a05m
PRODUCT_BRAND := samsung
PRODUCT_MODEL := SM-A055F
PRODUCT_MANUFACTURER := samsung

# Bootloader and Recovery
TARGET_BOOTLOADER_BOARD_NAME := a05m
BOARD_RECOVERY_IMAGE_PREPARE := true

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=userdebug
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x14f88000 --tags_offset 0x13f88000 --pagesize 2048
TARGET_PREBUILT_KERNEL := kernel/samsung/mt6768/arch/arm64/boot/Image.gz
TARGET_PREBUILT_RECOVERY_KERNEL := kernel/samsung/mt6768/arch/arm64/boot/Image.gz

# Platform
TARGET_BOARD_PLATFORM := mt6768
TARGET_BOARD_PLATFORM_GPU := mali-g52

# CPU and Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true

# Partitions (MT6768 A05m layout)
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2516582400
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_USERDATAIMAGE_PARTITION_SIZE := 10737418240

# File systems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# TWRP Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
RECOVERY_VARIANT := twrp
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
RECOVERY_GRAPHICS_USE_LINKER := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 150

# TWRP Flags
TW_THEME := portrait_hdpi
TW_SCREEN_RES_X := 720
TW_SCREEN_RES_Y := 1600
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INCLUDE_NTFS_3G := true
TW_USE_NEW_MINADBD := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true

# Storage and Mount Points
TARGET_RECOVERY_FSTAB := device/samsung/a05m/recovery.fstab
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_NO_KERNEL := false

# Debugging
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true

# Hardware
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_BDADDR_PATH := /data/misc/bd_addr
BOARD_HAVE_SAMSUNG_AUDIO := true
BOARD_USES_ALSA_AUDIO := true
TARGET_AUDIO_USE_LEGACY_MIXER := true
